name: Fetch 360 skins

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-skins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make assets folder
        run: mkdir -p assets

      - name: Download 360 background images
        run: |
          curl -L "https://upload.wikimedia.org/wikipedia/commons/4/4a/360-degree_Panorama_of_the_Southern_Sky.jpg" -o assets/nightsky.jpg
          curl -L "https://upload.wikimedia.org/wikipedia/commons/f/f9/Chilliwack_Lake_panorama.jpg" -o assets/lake_forest.jpg
          curl -L "https://upload.wikimedia.org/wikipedia/commons/6/68/Times_Square_June_2013.jpg" -o assets/city.jpg
          curl -L "https://upload.wikimedia.org/wikipedia/commons/f/f1/Leuzenberg_Panorama_01.jpg" -o assets/village.jpg
          curl -L "https://upload.wikimedia.org/wikipedia/commons/3/34/Aerial_panorama_of_Yerevan_Downtown_during_Air_Balloon_Festival_2023.jpg" -o assets/balloons.jpg

      - name: Create ZIP
        run: |
          cd assets
          zip -r skins.zip nightsky.jpg lake_forest.jpg city.jpg village.jpg balloons.jpg
          cd ..

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: skins
          path: assets/skins.zip

      - name: Commit & push images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add 360° skins (night sky, lake, city, village, balloons)"
          file_pattern: "assets/*.jpg assets/skins.zip"