
name: Fetch 360 skins

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-skins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Make assets folder
        run: mkdir -p assets

      - name: Download images (Wikimedia Special:FilePath)
        run: |
          curl -L "https://commons.wikimedia.org/wiki/Special:FilePath/360-degree%20Panorama%20of%20the%20Southern%20Sky.jpg" -o assets/nightsky.jpg
          curl -L "https://commons.wikimedia.org/wiki/Special:FilePath/Chilliwack%20Lake%20panorama.jpg" -o assets/lake_forest.jpg
          curl -L "https://commons.wikimedia.org/wiki/Special:FilePath/Times%20Square%20June%202013.jpg" -o assets/city.jpg
          curl -L "https://commons.wikimedia.org/wiki/Special:FilePath/Leuzenberg%20Panorama%2001.jpg" -o assets/village.jpg
          curl -L "https://commons.wikimedia.org/wiki/Special:FilePath/Aerial%20panorama%20of%20Yerevan%20Downtown%20during%20Air%20Balloon%20Festival%202023.jpg" -o assets/balloons.jpg

      - name: Create ZIP
        run: |
          cd assets
          zip -r skins.zip nightsky.jpg lake_forest.jpg city.jpg village.jpg balloons.jpg
          cd ..

      - name: Upload ZIP artifact
        uses: actions/upload-artifact@v4
        with:
          name: skins
          path: assets/skins.zip

      - name: Commit & push images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Add 360° skins (night sky, lake, city, village, balloons)"
          file_pattern: "assets/*.jpg assets/skins.zip"